FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python", "app.py"]

# docker run -d \
#   --name my-python-app \
#   -p 8080:5000 \
#   -e ENV=production \
#   -v "$(pwd)/logs:/app/logs" \
#   myapp:1.0